### ISSUE TITLE
learning 2 stage DBN

### ISSUE THREAD

**Issue by indu-bodala** [sambofra/bnstruct#25]
Hi, 

I have a dataset with 16 nodes and 5 time steps. When I use 'learn.dynamic.network' to learn the structure, the resulting structure is learning possible edges between 80 nodes (16x5). The good thing is that there are no edges from a node at t to any node at t-1, i.e the edges don't go back in time. But I also want to impose limitations such that nodes at t are influenced only by the present (t) and previous (t-1) time steps only. Is there a way to do this? Currently, I am seeing edges from time step 1 to all consequent time steps in the learnt network.

Thank you very much.

**Comment by albertofranzin** [comment]
Hi,

you can allow or forbid edges between specific layers with the `layer.struct` parameter. It takes a binary matrix where a cell `(i,j)`is `1` if nodes in layer `j` can have incoming arcs from nodes in layer `i`, and `0` otherwise.

**Comment by indu-bodala** [comment]
Is `layer.struct` parameter related to `layering` parameter? I was actually using `layering` to determine within time-slice structure.

**Comment by albertofranzin** [comment]
Yes, they are related.

A `layering` partitions the nodes into layers. For a dynamic BN, the default layering is the temporal one, so your 80 nodes will be divided into 16 nodes at layer `1`, 16 nodes at layer `2`, etc. If you don't provide any layering, `learn.dynamic.network` will use 
```
c(rep(1,16), rep(2,16), rep(3,16), rep(4,16), rep(5,16))
```
You can provide an additional subdivision for each time layer, for example `c(rep(1,8),rep(2,8))`. In this case, the whole DBN will have a total of 10 layers.

In what follows, let's assume you have the five default layers, numbered `1` to `5`. The corresponding `layer.struct` will be the 5x5 matrix
```
1 1 0 0 0
0 1 1 0 0
0 0 1 1 0
0 0 0 1 1
0 0 0 0 1
```
where the diagonal is `1` because each layer can have arcs between variables in the same time step, the additional `1`s allow the presence of arcs from layer `1` to layer `2` but not farther than that, from layer `2` to layer `3` but not farther than that, etc, and `0` for all the other possibilities.

**Comment by indu-bodala** [comment]
Thanks a lot! This is very helpful.

**Comment by indu-bodala** [comment]
Hello,

When I'm learning a two time-slice DBN, I also noticed that the learnt structure for within time-slice differs for each time-slice. Do you have any thoughts on how to deal with/represent this?

**Comment by albertofranzin** [comment]
Hello,

this depends on the data you have, and most likely on the availability of a limited number of observations. You could try to use bootstrap to see whether the arcs are imposed because of a real detected causal relationship, or simply because MMHC needs to impose a direction on an edge.

If you already know the presence/absence of arcs between specific variables (or infer some with a boostrap-based exploration) you can provide this information with mandatory/forbidden edges.

**Comment by indu-bodala** [comment]
Thanks! I will try bootstrapping.

**Comment by indu-bodala** [comment]
I tried bootstrapping as follows:

```{r}
dataset <- bootstrap(dataset, num.boots = 50, seed = 12)

RC_dbn_boot <- learn.dynamic.network(dataset, 
                                num.time.steps = 2,
                                bootstrap = TRUE,
                                layering = layers)

wstrct <- wpdag(RC_dbn_boot)
wstrct <- wpdag/50
wstrct <- wstrct >0.5
wstrct <- 1*wstrct
```
I have a wpdag with values from 0 to 50. I divided the matrix by 50 and assigned the values >0.5 to 1. May I check what threshold is reasonable?

This gives a matrix `wstrct` which still has different intra structure for each time-slice. Do you think it is okay to replace both the intra matrices with the connections from both timeslices as follows?

```
intra <- wstrct[1:16,1:16] | wstrct[17:32,17:32]
intra <- 1*intra

wstrct[1:16, 1:16] <- intra
wstrct[17:32,17:32] <- intra
```

I learnt the network again without bootstrap and tried replacing the dag of RC_dbn with `wstrct` and tried to re-learn the parameters as follows:

```
dag(RC_dbn_noboot) <- wstrct
RC_dbn_new <- learn.params(RC_dbn_noboot, dataset)
```
I think this is not working as I do not see any difference between the parameters learn for `RC_dbn_noboot` and `RC_dbn_new`.

**Comment by albertofranzin** [comment]
Hi, sorry for the late reply. 

In this context, bootstrap is a way of learning a structure in a more robust way, in case of scarce data, by learning the structure multiple times and aggregating this information together. Because of this, sometimes you can observe an arc A -> B and sometimes an arc B -> A. When all this information is put together, you don't have a Bayesian Network (so, for example you don't learn the parameters) but a different object that gives anyway some information about the relationships between the variables that can be inferred from the available data. You consistently observe A -> B and therefore be sure about its presence in the generating process, you can observe it only sometimes, and thus consider it a weaker connection, and sometimes you observe it in both directions, meaning that, from the available data, you can say that the two variables are related but you cannot establish who influences who (e.g. there may be some latent variable).

So, that's the sort of information you can get by learning a network with bootstrap. It is not really correct to fix a threshold and set the arcs based on that, because you have no real support for that. Likewise, joining the substructures with an `or` is also an operation that has no basis from what can be inferred from the available data.

Though, you could combine the outcome of the bootstrap-based learning with your knowledge about the generating process to inform a new learning task (mandatory or forbidden edges, or manually defining the structure). But that requires your knowledge about the process, and I don't think it is something that can be applied as a general rule.

In the end, everything depends on the data available. Bootstrap can be useful for estimating the confidence in the presence of each edge, but there is no way to replace more observations in the dataset.
